### ISSUE TITLE
Super basic CI for Chime

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#180]

**Comment by bsmithgall** [comment]
+ [ ] Script (myabe [fabric](http://www.fabfile.org/)? maybe just some makefiles?) to boot up a box with Chime on it
+ [ ] Find/create an editable file
+ [ ] Make sure that it can be previewed

**Comment by bsmithgall** [comment]
@wpietri could you put a sample hostfile somewhere (or just send it in slack)?

**Comment by bsmithgall** [comment]
@wpietri Was chatting with @tmaybe about this -- this should probably do something like use selenium to try to do steps (2) and (3) above, right?

**Comment by bsmithgall** [comment]
Also, `jekyll/install-jekyll.sh` takes forever to run. Is there anything that can be done about that?

**Comment by wpietri** [comment]
I think virtual browser tests would be awesome. But for this card I'd
settle for something more basic. E.g., something like Python's Twill (which
I haven't used, but looks equivalent to tools I've used/built in the past).
I say that only because my previous experience with Selenium was that it
was a beast to get running, but perhaps it has improved (or perhaps there's
another good alternative these days).

On Tue, May 5, 2015 at 2:17 PM, Ben Smithgall <notifications@github.com>
wrote:

> @wpietri <https://github.com/wpietri> Was chatting with @tmaybe
> <https://github.com/tmaybe> about this -- this should probably do
> something like use selenium to try to do steps (2) and (3) above, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/ceviche-cms/issues/180#issuecomment-99225086>
> .
>



-- 
William Pietri <william@codeforamerica.org> <william@codeforamerica.org>
Engineering Director, Digital Front Door, Code for America
<http://www.codeforamerica.org/>

**Comment by bsmithgall** [comment]
> twill strives to be a complete implementation of a Web browser, omitting only JavaScript support.

Will this work re: Persona?

**Comment by wpietri** [comment]
Regarding Twill, no idea. Also no idea if it's the best library. But in the past I have occasionally faked the JS activity, so JS isn't necessarily a barrier. E.g., if Persona used JS to redirect to a different link, I'd just tell my fake browser to go to the link at the right time.

Regarding the slow build, most of the time is taken up by  building Ruby from scratch. The obvious solution there is to cache those results, and Docker would be one way of doing that, but I haven't thought a ton about it.

**Comment by bsmithgall** [comment]
Unfortunately, I think JS might be required to get persona to behave properly (defer to @migurski who knows more and/or if there is a possible end-around that could be used).

**Comment by wpietri** [comment]
Usually in cases like that the JS does something reasonably predictable, which is what I'd fake. But that route can be more work than just doing it right, so I'd say the path is up to you.
